# https://chaos-mesh.dev/reference/release-2.1/
# https://chaos-mesh.org/docs/
apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: asp-platform
spec:
  entry: entry
  templates:
    - name: entry
      templateType: Serial
      children:
        - network-partition
    - name: network-partition
      deadline: 60s
      templateType: NetworkChaos
      networkChaos:
        action: partition
        direction: both
        target:
          mode: all
          selector:
            namespaces:
              - pulsar-cluster
        mode: fixed-percent
        value: '50'
        selector:
          namespaces:
            - pulsar-cluster
          labelSelectors:
            cluster: pulsar-asp