# https://chaos-mesh.dev/reference/release-2.1/
# https://chaos-mesh.org/docs/
apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: asp-platform
spec:
  entry: entry
  templates:
    - name: entry
      templateType: Serial
      children:
        - network-zookeeper
        - network-broker
        - network-bookie
    - name: network-zookeeper
      deadline: 30s
      templateType: NetworkChaos
      networkChaos:
        action: corrupt
        direction: to
        corrupt:
          corrupt: '50'
          correlation: '50'
        mode: fixed-percent
        value: '30'
        selector:
          namespaces:
            - pulsar-cluster
          labelSelectors:
            cluster: pulsar-asp
            component: zookeeper
    - name: network-broker
      deadline: 30s
      templateType: NetworkChaos
      networkChaos:
        action: corrupt
        direction: to
        corrupt:
          corrupt: '50'
          correlation: '50'
        mode: fixed-percent
        value: '50'
        selector:
          namespaces:
            - pulsar-cluster
          labelSelectors:
            cluster: pulsar-asp
            component: broker
    - name: network-bookie
      deadline: 30s
      templateType: NetworkChaos
      networkChaos:
        action: corrupt
        direction: to
        corrupt:
          corrupt: '50'
          correlation: '50'
        mode: fixed-percent
        value: '50'
        selector:
          namespaces:
            - pulsar-cluster
          labelSelectors:
            cluster: pulsar-asp
            component: bookie