# https://chaos-mesh.dev/reference/release-2.1/
# https://chaos-mesh.org/docs/
apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: asp-platform
spec:
  entry: entry
  templates:
    - name: entry
      templateType: Serial
      children:
        - network-corrupt
    - name: network-corrupt
      deadline: 60s
      templateType: NetworkChaos
      networkChaos:
        action: corrupt
        direction: to
        target:
          mode: all
          selector:
            namespaces:
              - pulsar-cluster
        corrupt:
          corrupt: '50'
          correlation: '50'
        mode: fixed-percent
        value: '70'
        selector:
          namespaces:
            - pulsar-cluster
          labelSelectors:
            cluster: pulsar-asp