# https://chaos-mesh.dev/reference/release-2.1/
# https://chaos-mesh.org/docs/
apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: asp-platform
spec:
  entry: entry
  templates:
    - name: entry
      templateType: Serial
      children:
        - stress-memory
    - name: stress-memory
      deadline: 60s
      templateType: StressChaos
      stressChaos:
        stressors:
          memory:
            workers: 1
            size: 60%
        mode: fixed-percent
        value: '30'
        selector:
          namespaces:
            - pulsar-cluster
          labelSelectors:
            cluster: pulsar-asp