# https://chaos-mesh.dev/reference/release-2.1/
# https://chaos-mesh.org/docs/
apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: asp-platform
spec:
  entry: entry
  templates:
    - name: entry
      templateType: Serial
      children:
        - pod-kill
    - name: pod-kill
      deadline: 30s
      templateType: PodChaos
      podChaos:
        action: pod-kill
        gracePeriod: 0
        mode: one
        selector:
          namespaces:
            - pulsar-cluster
          labelSelectors:
            cluster: pulsar-asp
            platform.ascentstream.com/app: pulsar