# https://chaos-mesh.dev/reference/release-2.1/
# https://chaos-mesh.org/docs/
apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: asp-platform
spec:
  entry: entry
  templates:
    - name: entry
      templateType: Serial
      children:
        - network-delay
    - name: network-delay
      deadline: 120s
      templateType: NetworkChaos
      networkChaos:
        action: delay
        direction: both
        target:
          mode: all
          selector:
            namespaces:
              - pulsar-cluster
        delay:
          latency: 1000ms
          correlation: '100'
          jitter: 0ms
        mode: fixed-percent
        value: '100'
        selector:
          namespaces:
            - pulsar-cluster
          labelSelectors:
            cluster: pulsar-asp