# https://chaos-mesh.dev/reference/release-2.1/
# https://chaos-mesh.org/docs/
apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: asp-platform
spec:
  entry: entry
  templates:
    - name: entry
      templateType: Serial
      children:
        - pod-kill
        - pod-failure
    - name: pod-kill
      deadline: 10s
      templateType: PodChaos
      podChaos:
        action: pod-kill
        gracePeriod: 3
        mode: fixed-percent
        value: '50'
        selector:
          namespaces:
            - pulsar-cluster
          labelSelectors:
            cluster: pulsar-asp
            component: broker
    - name: pod-failure
      deadline: 30s
      templateType: PodChaos
      podChaos:
        action: pod-failure
        mode:  fixed-percent
        value: '30'
        selector:
          namespaces:
            - pulsar-cluster
          labelSelectors:
            cluster: pulsar-asp
            component: broker