# Copyright [2023] [AscentStream]. All rights reserved.
#
# Licensed under the [Your License Name] License.
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# [http://ascentstream.com/]
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For questions and inquiries, please contact [Your Contact Email].

# Default values for asp-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

## Namespace to deploy operator
# NOTE: Make the default namespace as empty. So it will fallback to use the namespace used for installing the helm
#       chart. Helm does not position it self as a namespace manager, as namespaces in kubernetes are considered as
#       a higher control structure that is not part of the application.
namespace: ""
namespaceCreate: false

deploy:
  # Specifies which cases the operator should be deployed in, available options are:
  # "default", indicates the operator should be deployed in the normal single cluster or in the member cluster within a multi-cluster.
  # "host", indicates the operator should be deployed in the host cluster within a multi-cluster.
  # "control", indicates the operator should be deployed in the control-plane cluster within a multi-cluster.
  type: "default"

clusterDomain: "cluster.local"

operator:
  image:
    repository: "ascentstream/asp-operator"
    tag: "v2.0.7"
    pullPolicy: "IfNotPresent"
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  livenessProbe:
    failureThreshold: 3
    exec:
      command: ["/manager", "--healthcheck"]
    initialDelaySeconds: 15
    periodSeconds: 20
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    failureThreshold: 3
    exec:
      command: ["/manager", "--healthcheck"]
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  extraEnv: []

multicluster:
  enabled: false
  syncEndpointSlice: false
  kubeconfig: ""
  interpreterWebhook:
    namespace: "karmada-system"
    replicas: 1
    service:
      type: ClusterIP
      port: 443
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
    certSecretName: "karmada-webhook-cert"
    kubeconfigSecretName: "kubeconfig"
  webhookConfiguration:
    caBundle: ""

configuration:
  clusterDomainMappings:
#    member1: "cluster01.local"
#    member2: "cluster02.local"
#    member3: "cluster03.local"

kubeRbacProxy:
  image:
    repository: "ascentstream/kube-rbac-proxy"
    tag: "v0.13.1"
    pullPolicy: "IfNotPresent"
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 5m
      memory: 64Mi

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "asp-manager"

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8443

nodeSelector: {}
tolerations: []
affinity: {}
workers: 1
terminationGracePeriodSeconds: 10
rbac:
  create: true
  # Restrict the controller to operate only in a single namespace instead of cluster-wide scope.
  namespaced: false
  # Additional namespaces to be monitored by the controller.
  # Use string format, separated by commas, e.g. "namespace1,namespace2".
  managedNamespaces: ""
  # Additional user rules for the controller's rbac
  rules: []
  # Specifies whether a ClusterRole and ClusterRoleBinding should be created for storageClass
  storageClass: true

crds:
  install: true
